name: Deploy Cloud Trading Bot

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: cloud-trading-bot
  REGION: us-west1

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          pip install -r requirements_Version9.txt
          pip install flask flask-cors gunicorn pytest

      - name: Test Python backend
        run: |
          echo "Testing backend configuration..."
          python -c "from backend.config import get_config; print('Backend config test passed')"
          echo "Testing API import..."
          python -c "from api import app; print('API import test passed')"
          echo "Backend tests completed successfully"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Test frontend build
        run: |
          cd frontend
          npm run build

  deploy-backend:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      # Use Artifact Registry (recommended)
      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-west1-docker.pkg.dev

      - name: Build Docker image
        run: |
          echo "Building Docker images..."
          docker build -t us-west1-docker.pkg.dev/$PROJECT_ID/cloud-trading-bot/$SERVICE_NAME:$GITHUB_SHA .
          docker build -t us-west1-docker.pkg.dev/$PROJECT_ID/cloud-trading-bot/$SERVICE_NAME:latest .
          echo "Docker images built successfully"

      - name: Push Docker image
        run: |
          docker push us-west1-docker.pkg.dev/$PROJECT_ID/cloud-trading-bot/$SERVICE_NAME:$GITHUB_SHA
          docker push us-west1-docker.pkg.dev/$PROJECT_ID/cloud-trading-bot/$SERVICE_NAME:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image us-west1-docker.pkg.dev/$PROJECT_ID/cloud-trading-bot/$SERVICE_NAME:$GITHUB_SHA \
            --platform managed \
            --region $REGION \
            --allow-unauthenticated \
            --memory 1Gi \
            --cpu 1 \
            --max-instances 10 \
            --min-instances 0 \
            --port 8080 \
            --set-env-vars "ENVIRONMENT=production,PYTHONPATH=/app"

      - name: Get service URL
        run: |
          SERVICE_URL=$(gcloud run services describe $SERVICE_NAME --platform managed --region $REGION --format 'value(status.url)')
          echo "Backend deployed to: $SERVICE_URL"
          echo "SERVICE_URL=$SERVICE_URL" >> $GITHUB_ENV

  deploy-frontend:
    needs: [test, deploy-backend]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Build frontend
        run: |
          cd frontend
          echo "Installing frontend dependencies..."
          npm install
          echo "Building frontend for production..."
          npm run build
          echo "Frontend built successfully"

      - name: Deploy to Firebase Hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          cd frontend
          echo "Deploying to Firebase Hosting..."
          firebase deploy --project ${{ secrets.FIREBASE_PROJECT_ID }} --token $FIREBASE_TOKEN --only hosting
          echo "Firebase Hosting deployment completed"
nly hosting
ting
