name: Deploy to Firebase Hosting on push to main

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          echo "Installing frontend dependencies..."
          npm install
          echo "Dependencies installed successfully"
        working-directory: ./frontend

      - name: Build app
        run: |
          echo "Building React application..."
          npm run build
          echo "Build completed successfully"
        working-directory: ./frontend

      - name: Set up Python for Functions
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Functions dependencies
        run: |
          echo "Installing Python dependencies for Firebase Functions..."
          pip install -r requirements.txt
          echo "Functions dependencies installed successfully"
        working-directory: ./functions

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate with Firebase
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_CLOUD_TRADING_BOT }}" > $HOME/firebase-service-account.json
          export GOOGLE_APPLICATION_CREDENTIALS="$HOME/firebase-service-account.json"
          firebase use cloud-trading-bot-468900
        working-directory: ./frontend

      - name: Deploy to Firebase (Hosting + Functions)
        run: |
          echo "Deploying both Firebase Hosting and Functions..."
          export GOOGLE_APPLICATION_CREDENTIALS="$HOME/firebase-service-account.json"
          firebase deploy --project cloud-trading-bot-468900 --non-interactive
          echo "Firebase deployment completed successfully"
        working-directory: ./frontend
